// Builds the Little Shop of Horrors page's data (site/little-shop/shop-data.js) and its verdict bundle
// (site/little-shop/verdict.js) from the recorded UC13 run. Nothing is typed by hand: every message, answer, name,
// model and spend comes from records.csv, and the verdict is src/core bundled for the browser.
//
//   bun scripts/uc13/little-shop.ts           write both files
//   bun scripts/uc13/little-shop.ts --check   exit 1 if either committed file differs from a fresh build

import { join } from "node:path";
import { CASE_IDS, loadExample, parseRecords } from "./arms.ts";
import { ARMS, EXAMPLE_DIR, RECORDS_REL, RUN_DIR, buildDemo, checkInputs, recordedInputs } from "./stage-demo.ts";

const ROOT = join(import.meta.dir, "..", "..");
export const DATA_OUT = join(ROOT, "site", "little-shop", "shop-data.js");
export const VERDICT_OUT = join(ROOT, "site", "little-shop", "verdict.js");
export const PAGE = join(ROOT, "site", "little-shop", "index.html");
export const VERDICT_ENTRY = join(ROOT, "src", "browser", "shop-verdict-global.ts");
export const RUN_URL = "https://github.com/breakoutwithai/jevnotjev/tree/main/docs/product/runs/2026-10-01-uc13-shop-bot";

export interface ShopData {
  readonly schema: "jnj-little-shop/1";
  readonly run_id: string;
  readonly run_date: string;
  readonly run_url: string;
  readonly source: string;
  readonly arms: readonly { readonly key: string; readonly name: string; readonly model: string; readonly spend_usd: number | null }[];
  readonly messages: readonly { readonly id: string; readonly text: string; readonly outputs: Readonly<Record<string, string>> }[];
  readonly records_csv: string;
}

export function buildData(csv: string, factSheet: string): ShopData {
  const demo = buildDemo(parseRecords(csv), factSheet, CASE_IDS);
  const runId = /^jnj-record\/1,([^,]+),/m.exec(csv)?.[1] ?? "";
  const runDate = /(\d{4}-\d{2}-\d{2})$/.exec(runId)?.[1];
  if (runDate === undefined) throw new Error(`run_id ${JSON.stringify(runId)} does not end in a date`);
  return {
    schema: "jnj-little-shop/1",
    run_id: runId,
    run_date: runDate,
    run_url: RUN_URL,
    source: RECORDS_REL,
    arms: demo.arms.map((a) => ({ key: a.key, name: a.name, model: a.model, spend_usd: demo.tally[a.key]?.cost_usd ?? null })),
    messages: demo.messages.map((m) => {
      const outputs: Record<string, string> = {};
      for (const a of ARMS) {
        const o = m.outputs[a.key];
        if (o === undefined) throw new Error(`${m.id}: no ${a.key} output`);
        outputs[a.key] = o.output;
      }
      return { id: m.id, text: m.text, outputs };
    }),
    records_csv: csv,
  };
}

const PREFIX = "window.JNJ_LITTLE_SHOP = ";
const DATA_HEADER = `/*
 * GENERATED by scripts/uc13/little-shop.ts from ${RECORDS_REL}. Do not edit; rerun the script.
 * Little Shop of Horrors seating data: the 40 recorded messages, each arm's recorded answer, each arm's spend
 * (sum of its cost_usd cells), and records.csv itself, which verdict.js labels with the visitor's calls.
 */
`;

export function shopScript(d: ShopData): string {
  return `${DATA_HEADER}${PREFIX}${JSON.stringify(d, null, 1)};\n`;
}

/** Reads the data object back out of a generated data script. */
export function readShopScript(js: string): unknown {
  const at = js.lastIndexOf(`\n${PREFIX}`) + 1;
  if (at === 0) throw new Error("no window.JNJ_LITTLE_SHOP assignment");
  return JSON.parse(js.slice(at + PREFIX.length).trim().replace(/;$/, ""));
}

const VERDICT_HEADER = `/*
 * GENERATED by scripts/uc13/little-shop.ts: src/browser/shop-verdict-global.ts bundled for the browser
 * (src/format validate, src/core metrics and verdict). Do not edit; rerun the script.
 */
`;

export async function bundleVerdict(entry = VERDICT_ENTRY): Promise<string> {
  const r = await Bun.build({ entrypoints: [entry], target: "browser", format: "iife", minify: false });
  const out = r.outputs[0];
  if (!r.success || out === undefined) throw new Error(`verdict bundle failed: ${r.logs.map(String).join("; ")}`);
  return `${VERDICT_HEADER}${await out.text()}`;
}

export interface Built { readonly data: string; readonly verdict: string }

export async function build(runDir = RUN_DIR, exampleDir = EXAMPLE_DIR): Promise<Built> {
  const csv = await Bun.file(join(runDir, "records.csv")).text();
  const recorded = recordedInputs(await Bun.file(join(runDir, "label.html")).text());
  checkInputs(recorded, await loadExample(exampleDir), parseRecords(csv));
  return { data: shopScript(buildData(csv, recorded.factSheet)), verdict: await bundleVerdict() };
}

export const USAGE = "usage: bun scripts/uc13/little-shop.ts [--check]";

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error(`${USAGE}\nunknown arguments: ${args.join(" ")}; nothing written`);
    process.exit(2);
  }
  const built = await build();
  if (args[0] === "--check") {
    const stale: string[] = [];
    if ((await Bun.file(DATA_OUT).text().catch(() => "")) !== built.data) stale.push("site/little-shop/shop-data.js");
    if ((await Bun.file(VERDICT_OUT).text().catch(() => "")) !== built.verdict) stale.push("site/little-shop/verdict.js");
    console.log(stale.length === 0 ? "little shop up to date" : `stale: ${stale.join(", ")}; run bun scripts/uc13/little-shop.ts`);
    process.exit(stale.length === 0 ? 0 : 1);
  }
  await Bun.write(DATA_OUT, built.data);
  await Bun.write(VERDICT_OUT, built.verdict);
  console.log(`wrote site/little-shop/shop-data.js (${built.data.length} bytes) and site/little-shop/verdict.js (${built.verdict.length} bytes)`);
}
