// Builds the Little Shop of Horrors page, its data (site/little-shop/shop-data.js), and its verdict bundle
// (site/little-shop/verdict.js) from the recorded UC13 run. Nothing is typed by hand: every message, answer, name,
// model and spend comes from records.csv, and the verdict is src/core bundled for the browser.
//
//   bun scripts/uc13/little-shop.ts           write the three files
//   bun scripts/uc13/little-shop.ts --check   exit 1 if a committed file differs from a fresh build

import { basename, join, relative, resolve } from "node:path";
import { escapeHtml } from "../../src/browser/results-loader.ts";
import { summariseRun } from "../shows/build-posters.ts";
import type { RunSummary } from "../../src/shows/posters.ts";
import { CASE_IDS, loadExample, parseRecords } from "./arms.ts";
import { ARMS, EXAMPLE_DIR, RECORDS_REL, RUN_DIR, buildDemo, checkInputs, recordedInputs } from "./stage-demo.ts";

const ROOT = join(import.meta.dir, "..", "..");
export const DATA_OUT = join(ROOT, "site", "little-shop", "shop-data.js");
export const VERDICT_OUT = join(ROOT, "site", "little-shop", "verdict.js");
export const PAGE = join(ROOT, "site", "little-shop", "index.html");
export const VERDICT_ENTRY = join(ROOT, "src", "browser", "shop-verdict-global.ts");
export const RUN_URL = "https://github.com/breakoutwithai/jevnotjev/tree/main/docs/product/runs/2026-10-01-uc13-shop-bot";

export interface ShopData {
  readonly schema: "jnj-little-shop/1";
  readonly run_id: string;
  readonly run_date: string;
  readonly run_url: string;
  readonly source: string;
  readonly fact_sheet: { readonly title: string; readonly lines: readonly string[] };
  readonly arms: readonly { readonly key: string; readonly name: string; readonly model: string; readonly spend_usd: number | null }[];
  readonly messages: readonly { readonly id: string; readonly text: string; readonly outputs: Readonly<Record<string, string>> }[];
  readonly records_csv: string;
}

export function buildData(csv: string, factSheet: string): ShopData {
  const rows = parseRecords(csv);
  const demo = buildDemo(rows, factSheet, CASE_IDS);
  const runId = rows[0]?.run_id ?? "";
  const runDate = /(\d{4}-\d{2}-\d{2})$/.exec(runId)?.[1];
  if (runDate === undefined) throw new Error(`run_id ${JSON.stringify(runId)} does not end in a date`);
  return {
    schema: "jnj-little-shop/1",
    run_id: runId,
    run_date: runDate,
    run_url: RUN_URL,
    source: RECORDS_REL,
    fact_sheet: demo.fact_sheet,
    arms: demo.arms.map((a) => ({ key: a.key, name: a.name, model: a.model, spend_usd: demo.tally[a.key]?.cost_usd ?? null })),
    messages: demo.messages.map((m) => {
      const outputs: Record<string, string> = {};
      for (const a of ARMS) {
        const o = m.outputs[a.key];
        if (o === undefined) throw new Error(`${m.id}: no ${a.key} output`);
        outputs[a.key] = o.output;
      }
      return { id: m.id, text: m.text, outputs };
    }),
    records_csv: csv,
  };
}

const PREFIX = "window.JNJ_LITTLE_SHOP = ";
const DATA_HEADER = `/*
 * GENERATED by scripts/uc13/little-shop.ts from ${RECORDS_REL}. Do not edit; rerun the script.
 * Little Shop of Horrors seating data: the fact sheet recorded with the run, the 40 recorded messages, each arm's recorded answer, each arm's spend
 * (sum of its cost_usd cells), and records.csv itself, which verdict.js labels with the visitor's calls.
 */
`;

export function shopScript(d: ShopData): string {
  return `${DATA_HEADER}${PREFIX}${JSON.stringify(d, null, 1)};\n`;
}

/** Reads the data object back out of a generated data script. */
export function readShopScript(js: string): unknown {
  const at = js.lastIndexOf(`\n${PREFIX}`) + 1;
  if (at === 0) throw new Error("no window.JNJ_LITTLE_SHOP assignment");
  return JSON.parse(js.slice(at + PREFIX.length).trim().replace(/;$/, ""));
}

const VERDICT_HEADER = `/*
 * GENERATED by scripts/uc13/little-shop.ts: src/browser/shop-verdict-global.ts bundled for the browser
 * (src/format validate, src/core metrics and verdict). Do not edit; rerun the script.
 */
`;

export async function bundleVerdict(entry = VERDICT_ENTRY): Promise<string> {
  const r = await Bun.build({ entrypoints: [entry], target: "browser", format: "iife", minify: false });
  const out = r.outputs[0];
  if (!r.success || out === undefined) throw new Error(`verdict bundle failed: ${r.logs.map(String).join("; ")}`);
  return `${VERDICT_HEADER}${await out.text()}`;
}

export interface Built { readonly data: string; readonly verdict: string; readonly page: string }

const RESULT_START = "<!-- BEGIN RECORDED RUN RESULT -->";
const RESULT_END = "<!-- END RECORDED RUN RESULT -->";

/** Replace the generated official-run summary; the visitor's own verdict below still comes from their calls. */
function resultPage(page: string, run: RunSummary): string {
  const line = (className: string, value: string | null): string => value === null ? "" : `<p class="${className}">${escapeHtml(value)}</p>`;
  const date = new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" }).format(new Date(`${run.folder.slice(0, 10)}T00:00:00Z`));
  const block = [RESULT_START,
    '<div class="recorded-run" aria-label="Recorded run result">',
    line("recorded-caption", `Recorded run, ${date}: ${run.labelledPaired} paired cases`),
    run.headline === null ? "" : `<h3 class="recorded-headline">${escapeHtml(run.headline)}</h3>`,
    line("recorded-verdict", run.verdict === null ? null : `Verdict: ${run.verdict}`),
    line("recorded-why", run.whyNotYet),
    "</div>", RESULT_END].filter(Boolean).join("\n        ");
  const start = page.indexOf(RESULT_START);
  const end = page.indexOf(RESULT_END);
  if ((start < 0) !== (end < 0)) throw new Error("little-shop page has one recorded-result marker but not the other");
  if (start >= 0) return page.slice(0, start) + block + page.slice(end + RESULT_END.length);
  const anchor = '<ul class="arms" id="arms"></ul>';
  if (!page.includes(anchor)) throw new Error("little-shop page has no programme arms anchor");
  return page.replace(anchor, `${block}\n        ${anchor}`);
}

export async function build(runDir = RUN_DIR, exampleDir = EXAMPLE_DIR, sourcePage?: string): Promise<Built> {
  const dir = resolve(runDir);
  const csv = await Bun.file(join(dir, "records.csv")).text();
  const recorded = recordedInputs(await Bun.file(join(dir, "label.html")).text());
  checkInputs(recorded, await loadExample(exampleDir), parseRecords(csv));
  const summary = await summariseRun(ROOT, relative(join(ROOT, "docs", "product", "runs"), dir));
  if (summary === null) throw new Error(`no run summary for ${dir}`);
  const run = { ...summary, folder: basename(dir) };
  return { data: shopScript(buildData(csv, recorded.factSheet)), verdict: await bundleVerdict(), page: resultPage(sourcePage ?? await Bun.file(PAGE).text(), run) };
}

export const USAGE = "usage: bun scripts/uc13/little-shop.ts [--check]";

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error(`${USAGE}\nunknown arguments: ${args.join(" ")}; nothing written`);
    process.exit(2);
  }
  const built = await build();
  if (args[0] === "--check") {
    const stale: string[] = [];
    if ((await Bun.file(DATA_OUT).text().catch(() => "")) !== built.data) stale.push("site/little-shop/shop-data.js");
    if ((await Bun.file(VERDICT_OUT).text().catch(() => "")) !== built.verdict) stale.push("site/little-shop/verdict.js");
    if ((await Bun.file(PAGE).text().catch(() => "")) !== built.page) stale.push("site/little-shop/index.html");
    console.log(stale.length === 0 ? "little shop up to date" : `stale: ${stale.join(", ")}; run bun scripts/uc13/little-shop.ts`);
    process.exit(stale.length === 0 ? 0 : 1);
  }
  await Bun.write(DATA_OUT, built.data);
  await Bun.write(VERDICT_OUT, built.verdict);
  await Bun.write(PAGE, built.page);
  console.log(`wrote site/little-shop/shop-data.js (${built.data.length} bytes), site/little-shop/verdict.js (${built.verdict.length} bytes), and site/little-shop/index.html`);
}
