/**
 * Case text for the persona packs P5 to P8 (Backstage starter packs). Every case is invented. The cases carry no
 * label: the tester labels them blind in Rehearsals, and an imported file without a label column behaves the same.
 */

export interface PersonaCase {
  readonly id: string;
  readonly input: string;
}

export const P5_CASES: readonly PersonaCase[] = [
  { id: "p5-17", input: "Title: MORNING ROUTINE that changed my life\nWatched: 4:40 of 8:00\nSummary: Says 'it changed my life' four times. The routine itself has not been listed yet." },
  { id: "p5-15", input: "Title: Learn the 12 major keys on guitar\nWatched: 2:15 of 10:00\nSummary: Plays the circle of fifths and names each key with its sharps or flats. Slow, but each key is new." },
  { id: "p5-30", input: "Title: Spanish numbers 1 to 20 for beginners\nWatched: 1:40 of 4:00\nSummary: Says each number twice with a slow repeat and a written card. Reaches 14 in the part watched." },
  { id: "p5-11", input: "Title: Intro to compound interest with a worked example\nWatched: 3:40 of 8:00\nSummary: Works 1,000 at 5 percent over 3 years year by year and shows the formula result matches." },
  { id: "p5-01", input: "Title: How to descale a kettle with white vinegar\nWatched: 3:10 of 9:40\nSummary: Shows the ratio (half water, half vinegar), a 20 minute soak, and the rinse step. Nothing repeated." },
  { id: "p5-28", input: "Title: Beginner 20 minute workout, no equipment\nWatched: 5:00 of 20:00\nSummary: Warm up, then squats and press ups with a count. The host chats between sets. Exercises are real but repeated." },
  { id: "p5-19", input: "Title: Is this crypto about to 100x?? (not financial advice)\nWatched: 3:30 of 7:00\nSummary: Shouting a coin name, a rocket emoji on screen, and a link in the description. No numbers or reasons given." },
  { id: "p5-23", input: "Title: Is this stock a buy? My honest view\nWatched: 4:30 of 10:00\nSummary: States one revenue figure and one risk, then spends two minutes on how long he has been investing. Verdict not given yet." },
  { id: "p5-20", input: "Title: Best budget laptop 2026: real benchmark results\nWatched: 4:10 of 10:30\nSummary: Shows battery hours, a fan noise reading, and a render time for three named laptops in a table." },
  { id: "p5-08", input: "Title: Epic fail compilation #88\nWatched: 2:00 of 15:00\nSummary: Clips of people falling over. Matches the title exactly. Each clip is a different fail, with no commentary." },
  { id: "p5-26", input: "Title: Explain Git branches with a train map\nWatched: 3:00 of 7:15\nSummary: Draws the main line, splits a branch, then merges it back. Each git command is shown beside the drawing." },
  { id: "p5-12", input: "Title: Daily vlog 412: nothing much\nWatched: 7:20 of 14:00\nSummary: Walks around a shop, says 'I dunno', buys nothing. No point or story so far." },
  { id: "p5-10", input: "Title: Fix a dripping tap washer in 5 steps\nWatched: 1:50 of 5:10\nSummary: Isolates the water, removes the handle, replaces the washer. Steps are numbered on screen." },
  { id: "p5-29", input: "Title: 12 facts you never knew (number 7 will shock you)\nWatched: 2:50 of 7:00\nSummary: Facts so far: water is wet, Monday follows Sunday, and the sky is above us. Each is followed by a pause and a countdown graphic." },
  { id: "p5-27", input: "Title: Why does bread go stale?\nWatched: 2:40 of 6:30\nSummary: Gives one reason, then repeats it with three different analogies. Third minute is a sponsor spot." },
  { id: "p5-02", input: "Title: You Won't BELIEVE What Happens Next\nWatched: 4:20 of 8:15\nSummary: Host recaps the intro three times, asks viewers to subscribe twice, and has not shown the thing from the title." },
  { id: "p5-07", input: "Title: Reacting to my old videos\nWatched: 6:10 of 12:00\nSummary: Laughs at clips for six minutes. No commentary beyond 'wow' and 'cringe'." },
  { id: "p5-16", input: "Title: How a bill becomes law in 4 minutes\nWatched: 1:30 of 4:00\nSummary: Draws the path from committee to floor vote to signature with a named example bill." },
  { id: "p5-13", input: "Title: Tiny house tour, part 2 of 3\nWatched: 3:10 of 12:00\nSummary: Slow tour of the kitchen with a few measurements mentioned. Host talks a lot about the weather. Some details are new, some padding." },
  { id: "p5-05", input: "Title: Python list comprehension in 6 minutes\nWatched: 2:30 of 6:00\nSummary: Writes two loops, converts each to a comprehension on screen, and runs both. Clear before and after." },
  { id: "p5-25", input: "Title: My cat learns to open a door\nWatched: 2:10 of 5:00\nSummary: Shows each attempt and how the cat finally reaches the handle. Short and as promised." },
  { id: "p5-22", input: "Title: Reading the comments on my last video\nWatched: 5:50 of 9:20\nSummary: Reads comments aloud and replies 'thanks!' to each. No new information about anything." },
  { id: "p5-24", input: "Title: Unboxing the new mystery gadget\nWatched: 3:20 of 6:00\nSummary: Opens the box slowly, then holds it up to the camera. The gadget has not been named or switched on." },
  { id: "p5-14", input: "Title: Is the moon landing real? Full proof\nWatched: 5:30 of 9:00\nSummary: Repeats one blurry photo and says 'think about it' over and over. No sources or claims checked." },
  { id: "p5-21", input: "Title: How to read a bus timetable\nWatched: 1:20 of 3:30\nSummary: Explains the rows, the times in the footnotes, and what 'school days only' means, with a real example grid." },
  { id: "p5-03", input: "Title: 10 HOURS of Rain Sounds\nWatched: 0:45 of 10:00:00\nSummary: Looped rain audio with a static image. Matches the title; nothing else is promised." },
  { id: "p5-18", input: "Title: History of the bicycle (documentary style)\nWatched: 6:00 of 18:00\nSummary: First six minutes cover the 1817 running machine and the penny-farthing with dates, then it moves into a long montage with music over it." },
  { id: "p5-04", input: "Title: Top 5 phones of the year (sponsored)\nWatched: 5:00 of 11:20\nSummary: Every phone gets the same line of praise and the same discount code. No specs or comparison given." },
  { id: "p5-06", input: "Title: Beginner sourdough, day one starter\nWatched: 4:00 of 7:30\nSummary: Gives flour and water weights in grams, jar size, and what bubbles to expect on day three." },
  { id: "p5-09", input: "Title: This ONE trick doctors hate\nWatched: 3:00 of 6:45\nSummary: Promises the trick at the end of the video. So far: a story about the host's neighbour and an ad read." },
];

export const P6_CASES: readonly PersonaCase[] = [
  { id: "p6-03", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A beauty salon owner asks for a booking tool that handles different services and time lengths\nSource: a small business forum\nPosted: 2 days ago" },
  { id: "p6-19", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Opinion piece on political changes to pet import rules\nSource: a national news site\nPosted: 2 days ago" },
  { id: "p6-30", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Thread: 'Walk-ins vs appointments for a small grooming shop, what works?'\nSource: a small business forum\nPosted: 2 days ago" },
  { id: "p6-23", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Groomer says she is thinking of retiring next year and wants to know how to sell her client list\nSource: a pet business community forum\nPosted: 1 day ago" },
  { id: "p6-17", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Same question as an earlier find: a groomer asks about booking tools (reposted word for word)\nSource: a second small business forum\nPosted: today" },
  { id: "p6-10", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: User asks which scheduling apps send text reminders to dog owners\nSource: a pet owner subreddit-style forum\nPosted: 1 day ago" },
  { id: "p6-13", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Article on how pet owners spend more on grooming each year, no mention of booking or scheduling\nSource: a pet industry newsletter\nPosted: 1 day ago" },
  { id: "p6-06", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Trade newsletter reports a regional groomers association is recommending online booking for members\nSource: a pet industry newsletter\nPosted: 2 days ago" },
  { id: "p6-11", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A mobile groomer shares frustration that her paper diary double booked two large dogs\nSource: a local business Facebook-style group post\nPosted: today" },
  { id: "p6-14", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Review of a new cat scratching post\nSource: a pet product review site\nPosted: 3 days ago" },
  { id: "p6-05", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Post complaining that no-show clients cost a salon about 40 a week and asking how others handle deposits\nSource: a pet business community forum\nPosted: 2 days ago" },
  { id: "p6-28", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: User asks which phone calendar app is best for a busy small business, no mention of pets\nSource: a small business forum\nPosted: today" },
  { id: "p6-24", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A hairdresser asks about booking apps for her salon\nSource: a small business forum\nPosted: 2 days ago" },
  { id: "p6-02", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Advert: 50 percent off dog shampoo this weekend only\nSource: a pet store promotional email\nPosted: today" },
  { id: "p6-26", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A new groomer asks how to keep track of repeat clients and their dogs' coat notes\nSource: a pet business community forum\nPosted: today" },
  { id: "p6-15", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Local news piece: grooming demand up in the area, salons booked three weeks out\nSource: a regional news site\nPosted: 3 days ago" },
  { id: "p6-16", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Question: 'Can anyone recommend software that lets customers pick a groomer and a time slot?'\nSource: a small business forum\nPosted: today" },
  { id: "p6-08", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A groomer asks about booking software, 6 days old, no replies yet\nSource: a small business forum\nPosted: 6 days ago" },
  { id: "p6-07", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A groomer asks about booking software\nSource: a small business forum\nPosted: 14 months ago" },
  { id: "p6-09", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Job listing for a veterinary receptionist in another country\nSource: a jobs board\nPosted: 1 day ago" },
  { id: "p6-29", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Thread about how to train a puppy to sit, 300 replies\nSource: a pet owner forum\nPosted: 3 days ago" },
  { id: "p6-20", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Salon owner asks for advice on how to cut cancellations without charging a fee\nSource: a pet business community forum\nPosted: 2 days ago" },
  { id: "p6-27", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Press release for a pet food brand launching a new kibble\nSource: a company press release page\nPosted: today" },
  { id: "p6-25", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Announcement: a grooming supply chain is hosting an online booking webinar next week\nSource: a pet industry newsletter\nPosted: 1 day ago" },
  { id: "p6-22", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Photo of a groomed poodle with the caption 'Look at that fluff!'\nSource: a pet owner photo group\nPosted: 1 day ago" },
  { id: "p6-01", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A groomer asks: 'Any simple booking tool for a one-person grooming van? Phone tag is eating my day.'\nSource: a small business owners forum, thread started by a user\nPosted: 1 day ago" },
  { id: "p6-12", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Spam: 'Make 500 a day from home, click here' posted under a grooming thread\nSource: a pet business community forum\nPosted: today" },
  { id: "p6-04", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Recipe for homemade dog treats with peanut butter\nSource: a pet owner blog\nPosted: 2 days ago" },
  { id: "p6-21", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: A groomer says her current booking tool charges per text and asks for cheaper options\nSource: an independent business owners forum\nPosted: 1 day ago" },
  { id: "p6-18", input: "Tracked project: Pawslot, an appointment app for dog groomers\nFound: Complaint that an unnamed grooming chain 'never answers the phone', no mention of booking\nSource: a local review site\nPosted: 3 days ago" },
];

export const P7_CASES: readonly PersonaCase[] = [
  { id: "p7-24", input: "Rubric line: States the purpose of a topic sentence and where it usually goes in a paragraph.\nStudent answer: It goes at the start. I am not sure what it does." },
  { id: "p7-19", input: "Rubric line: Converts 3/4 to a percentage and shows the step.\nStudent answer: 3/4 is 34 percent." },
  { id: "p7-18", input: "Rubric line: Translates 'I have two brothers' into correct Spanish.\nStudent answer: Tengo dos hermanos. (No accent or punctuation errors, but written in all capitals.)" },
  { id: "p7-10", input: "Rubric line: Translates 'I have two brothers' into correct Spanish.\nStudent answer: Tengo dos hermanos." },
  { id: "p7-30", input: "Rubric line: States what a mean average is and calculates it for 2, 4 and 9.\nStudent answer: The mean is the sum divided by the number of values. 2 plus 4 plus 9 is 15, divided by 3 gives 5." },
  { id: "p7-04", input: "Rubric line: States the formula for the area of a triangle and gives the correct result for base 6 and height 4.\nStudent answer: Area is base times height, so 6 times 4 is 24." },
  { id: "p7-09", input: "Rubric line: Translates 'I have two brothers' into correct Spanish.\nStudent answer: Yo tiene dos hermano." },
  { id: "p7-11", input: "Rubric line: Defines a noun and gives one example.\nStudent answer: A noun is a word that names a person, place or thing, for example 'table'." },
  { id: "p7-03", input: "Rubric line: Names the process and states its two inputs (photosynthesis: water and carbon dioxide).\nStudent answer: Photosynthesis. It uses water and, uh, gas from the air." },
  { id: "p7-28", input: "Rubric line: Defines a noun and gives one example.\nStudent answer: A noun names something, like London." },
  { id: "p7-05", input: "Rubric line: States the formula for the area of a triangle and gives the correct result for base 6 and height 4.\nStudent answer: Area is half times base times height, so half of 6 times 4 is 12." },
  { id: "p7-25", input: "Rubric line: States the purpose of a topic sentence and where it usually goes in a paragraph.\nStudent answer: A topic sentence tells the reader the main idea and it usually comes first in the paragraph." },
  { id: "p7-01", input: "Rubric line: Names the process and states its two inputs (photosynthesis: water and carbon dioxide).\nStudent answer: Photosynthesis. Plants take in water through the roots and carbon dioxide through the leaves." },
  { id: "p7-21", input: "Rubric line: Names the three states of matter and gives one example of each.\nStudent answer: Solid like ice, liquid like water, and gas like steam." },
  { id: "p7-12", input: "Rubric line: Defines a noun and gives one example.\nStudent answer: A noun is a word. Like table or chair." },
  { id: "p7-02", input: "Rubric line: Names the process and states its two inputs (photosynthesis: water and carbon dioxide).\nStudent answer: Photosynthesis. Plants make food using sunlight." },
  { id: "p7-06", input: "Rubric line: Identifies the cause of the 1666 Great Fire of London and one reason it spread.\nStudent answer: It started in a bakery in Pudding Lane and spread because the houses were wooden and close together." },
  { id: "p7-16", input: "Rubric line: Explains why a verb must agree with its subject, using one example.\nStudent answer: A verb has to match its subject in number, so we say 'she runs' but 'they run'." },
  { id: "p7-29", input: "Rubric line: Names two causes of the water cycle's rain stage (evaporation and condensation) in order.\nStudent answer: Rain happens when clouds get full and fall down." },
  { id: "p7-13", input: "Rubric line: Identifies the cause of the 1666 Great Fire of London and one reason it spread.\nStudent answer: It began in a bakery. It spread a lot." },
  { id: "p7-07", input: "Rubric line: Identifies the cause of the 1666 Great Fire of London and one reason it spread.\nStudent answer: The fire was started by the Dutch during a war." },
  { id: "p7-22", input: "Rubric line: Names the three states of matter and gives one example of each.\nStudent answer: Solid, liquid, gas, and plasma is also one." },
  { id: "p7-14", input: "Rubric line: States the boiling point of water at sea level in Celsius and says what happens to it at altitude.\nStudent answer: Water boils at 100 degrees Celsius." },
  { id: "p7-15", input: "Rubric line: States the boiling point of water at sea level in Celsius and says what happens to it at altitude.\nStudent answer: Water boils at 100 degrees Celsius at sea level and boils at a lower temperature higher up a mountain." },
  { id: "p7-17", input: "Rubric line: Explains why a verb must agree with its subject, using one example.\nStudent answer: Because it sounds better when you say it out loud." },
  { id: "p7-23", input: "Rubric line: Converts 3/4 to a percentage and shows the step.\nStudent answer: 75 percent, because 3/4 is the same as 75/100." },
  { id: "p7-20", input: "Rubric line: Converts 3/4 to a percentage and shows the step.\nStudent answer: 3 divided by 4 is 0.75, and 0.75 times 100 is 75 percent." },
  { id: "p7-26", input: "Rubric line: Names two causes of the water cycle's rain stage (evaporation and condensation) in order.\nStudent answer: Water evaporates from the sea and rises, then it cools and condenses into clouds, which makes rain." },
  { id: "p7-08", input: "Rubric line: States the formula for the area of a triangle and gives the correct result for base 6 and height 4.\nStudent answer: Half base times height, which is 12. (Written as 'half b h = 12' with no numbers shown.)" },
  { id: "p7-27", input: "Rubric line: States what a mean average is and calculates it for 2, 4 and 9.\nStudent answer: The mean is the middle number, which is 4." },
];

export const P8_CASES: readonly PersonaCase[] = [
  { id: "p8-22", input: "Event: Startup founders mixer\nMember message: Invest in my new coin, guaranteed 10x in a month, sign up through this link.\nContext: Posted in four rooms by the same member." },
  { id: "p8-16", input: "Event: Language exchange night\nMember message: Hola, I'm learning Portuguese. Anyone want to practise for 10 minutes?\nContext: In the language pairing room." },
  { id: "p8-10", input: "Event: Remote book club meet-up\nMember message: Thanks for hosting, Priya. See you all next week!\nContext: Posted at the end of the session." },
  { id: "p8-29", input: "Event: Run club social\nMember message: I know where you live. Reply to me or I will come over.\nContext: Private message to a member who blocked the sender." },
  { id: "p8-17", input: "Event: Language exchange night\nMember message: Hey, you are so beautiful. Send me a picture of yourself right now.\nContext: Private message to a member who has not replied." },
  { id: "p8-06", input: "Event: Remote book club meet-up\nMember message: Loved the pick this month! Who else found the ending a bit rushed?\nContext: Posted in the book discussion room." },
  { id: "p8-19", input: "Event: Language exchange night\nMember message: I don't want to be here anymore. Nothing matters to me.\nContext: Posted in the general room after a long silence." },
  { id: "p8-26", input: "Event: Run club social\nMember message: Anyone doing the 5k on Saturday? I'm a slow jogger, so no pressure!\nContext: Posted in the weekend plans channel." },
  { id: "p8-28", input: "Event: Language exchange night\nMember message: That's the third time you got the grammar wrong, you really aren't trying.\nContext: Public message to a learner who has been getting help for a week." },
  { id: "p8-21", input: "Event: Startup founders mixer\nMember message: Hello all, I run a small bakery software tool. Looking to swap notes with other solo founders.\nContext: Self-introduction in the intro channel, one post only." },
  { id: "p8-08", input: "Event: Online speed networking for designers\nMember message: Your portfolio is honestly pretty weak compared to the others here.\nContext: Public reply to a portfolio link, the member asked for feedback." },
  { id: "p8-15", input: "Event: Gardening swap hall\nMember message: Lovely garden photos, Sam! What variety is the climbing rose?\nContext: Reply under another member's photo." },
  { id: "p8-20", input: "Event: Language exchange night\nMember message: Sorry, my mic cut out. Can you say that again?\nContext: Posted during a pair call." },
  { id: "p8-30", input: "Event: Run club social\nMember message: Welcome Alex! Glad you could join.\nContext: Reply to a new member's intro." },
  { id: "p8-27", input: "Event: Run club social\nMember message: You are way too slow, you should not be in this club.\nContext: Directed at a named member, who has asked others to stop commenting." },
  { id: "p8-02", input: "Event: Online speed networking for designers\nMember message: You're an idiot and your portfolio is trash. Quit before you embarrass yourself.\nContext: Direct reply to another member's shared portfolio link." },
  { id: "p8-13", input: "Event: Remote book club meet-up\nMember message: Drop me a note at my email if you want to talk about books outside the group.\nContext: Posted in the main hall, no actual address included." },
  { id: "p8-07", input: "Event: Remote book club meet-up\nMember message: Call me on 555 0100 tonight, I'll tell you where I live.\nContext: Private message to a member who joined today." },
  { id: "p8-01", input: "Event: Online speed networking for designers\nMember message: Hi everyone, I'm a freelance illustrator from the coast. Happy to chat about portfolio tips.\nContext: First message from a new member." },
  { id: "p8-24", input: "Event: Startup founders mixer\nMember message: Here is my home address and my bank details, can someone help me with my invoice.\nContext: Posted publicly in the main hall." },
  { id: "p8-09", input: "Event: Remote book club meet-up\nMember message: I told you twice to leave me alone. Why do you keep messaging me?\nContext: Message from a member to a moderator, forwarding three unwanted DMs from the same person." },
  { id: "p8-03", input: "Event: Startup founders mixer\nMember message: I'd love to show you my new product, can I send you my deck on email?\nContext: First DM, member has not replied to any earlier message." },
  { id: "p8-14", input: "Event: Gardening swap hall\nMember message: Nobody here likes you, Sam. Go away.\nContext: Posted publicly under Sam's photo, third message in an hour." },
  { id: "p8-12", input: "Event: Gardening swap hall\nMember message: Send 50 in gift cards and I will ship you a rare plant, trust me.\nContext: From an account created one hour ago." },
  { id: "p8-04", input: "Event: Online speed networking for designers\nMember message: Buy my followers package! 10k followers for 20 dollars, message me now!!!\nContext: Same text sent to five different rooms in two minutes." },
  { id: "p8-18", input: "Event: Run club social\nMember message: Ugh, I'm so done with today. Too much work, too little sleep.\nContext: Posted in the general room, member usually cheerful." },
  { id: "p8-25", input: "Event: Startup founders mixer\nMember message: Great talk! Could you share the slide on pricing tiers?\nContext: Reply to the speaker in the Q&A channel." },
  { id: "p8-11", input: "Event: Gardening swap hall\nMember message: I have spare tomato seedlings if anyone wants to swap for herbs.\nContext: Posted in the swap board channel." },
  { id: "p8-23", input: "Event: Gardening swap hall\nMember message: Check out my shop for cheap pots, link below, 10 percent off for hall members.\nContext: One post in the swap board, links to the member's own page." },
  { id: "p8-05", input: "Event: Online speed networking for designers\nMember message: Does anyone know if the next round starts at 3 or 3:15?\nContext: Reply in the main hall channel." },
];
