// Builds the public page's CSV loader (site/results-loader.js): src/browser/results-loader-global.ts bundled for the
// browser with src/format validate and src/core metrics and verdict. Same pattern as scripts/uc13/little-shop.ts.
//
//   bun scripts/build-loader.ts           write the file
//   bun scripts/build-loader.ts --check   exit 1 if the committed file differs from a fresh build

import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
export const LOADER_OUT = join(ROOT, "site", "results-loader.js");
export const LOADER_ENTRY = join(ROOT, "src", "browser", "results-loader-global.ts");

const HEADER = `/*
 * GENERATED by scripts/build-loader.ts: src/browser/results-loader-global.ts bundled for the browser
 * (src/format validate, src/core metrics and verdict). Reads the chosen file in the browser only; sends nothing. Do not edit; rerun the script.
 */
`;

export async function bundleLoader(entry = LOADER_ENTRY): Promise<string> {
  const r = await Bun.build({ entrypoints: [entry], target: "browser", format: "iife", minify: false });
  const out = r.outputs[0];
  if (!r.success || out === undefined) throw new Error(`loader bundle failed: ${r.logs.map(String).join("; ")}`);
  return `${HEADER}${await out.text()}`;
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error("usage: bun scripts/build-loader.ts [--check]");
    process.exit(2);
  }
  const built = await bundleLoader();
  if (args[0] === "--check") {
    const same = (await Bun.file(LOADER_OUT).text().catch(() => "")) === built;
    console.log(same ? "loader up to date" : "stale: site/results-loader.js; run bun scripts/build-loader.ts");
    process.exit(same ? 0 : 1);
  }
  await Bun.write(LOADER_OUT, built);
  console.log(`wrote site/results-loader.js (${built.length} bytes)`);
}
