// Builds the replay page's data (site/replay/replay-data.js) from the repo's own record files: every case, answer,
// label and cost comes from the CSV, and the tallies and flags from src/evidence/replay.ts. Same pattern as
// scripts/uc13/little-shop.ts.
//
//   bun scripts/replay-data.ts           write the file
//   bun scripts/replay-data.ts --check   exit 1 if the committed file differs from a fresh build

import { join } from "node:path";
import { RUN_SOURCES, parseRun, type ReplayRun, type RunSource } from "../src/evidence/replay.ts";
import { MIN_PAIRED } from "../src/core/verdict.ts";

const ROOT = join(import.meta.dir, "..");
export const REPLAY_OUT = join(ROOT, "site", "replay", "replay-data.js");
export const REPO_URL = "https://github.com/breakoutwithai/jevnotjev";

export interface ReplayData {
  readonly schema: "jnj-replay/1";
  readonly min_paired: number;
  readonly runs: readonly (ReplayRun & { readonly sourceUrl: string })[];
}

export async function buildReplay(root = ROOT): Promise<ReplayData> {
  const runs = await Promise.all(RUN_SOURCES.map(async (s) => ({
    ...parseRun(await Bun.file(join(root, s.file)).text(), s),
    sourceUrl: `${REPO_URL}/blob/main/${s.file}`,
  })));
  return { schema: "jnj-replay/1", min_paired: MIN_PAIRED, runs };
}

const PREFIX = "window.JNJ_REPLAY = ";
const header = (from: string): string => `/*
 * GENERATED by scripts/replay-data.ts from ${from}.
 * Do not edit; rerun the script. Each run's cases, answers, labels and costs as recorded, the tally after each case,
 * each method's totals, and the incomplete-evidence flags (src/evidence/replay.ts).
 */
`;

export function replayScript(d: ReplayData, from: string = RUN_SOURCES.map((s) => s.file).join(", ")): string {
  return `${header(from)}${PREFIX}${JSON.stringify(d)};\n`;
}

/** Reads the data object back out of a generated data script. */
export function readReplayScript(js: string): unknown {
  const at = js.lastIndexOf(`\n${PREFIX}`) + 1;
  if (at === 0) throw new Error("no window.JNJ_REPLAY assignment");
  return JSON.parse(js.slice(at + PREFIX.length).trim().replace(/;$/, ""));
}

export const USAGE = "usage: bun scripts/replay-data.ts [--check]\n" +
  "       bun scripts/replay-data.ts --records <csv> --out <file.js> [--key k] [--title t] [--page-by 10] [--extra decisions]\n" +
  "                                  [--spotlight <caseKey>=<heading>] [--source-url <url>]   one run from a records file kept outside the repo";

export interface CustomArgs {
  readonly records: string;
  readonly out: string;
  readonly source: RunSource;
  readonly sourceUrl: string;
}

const CUSTOM_FLAGS = ["--records", "--out", "--key", "--title", "--page-by", "--extra", "--spotlight", "--source-url"];
const DEFAULT_NAME = "Recorded run";

function named(rest: Omit<RunSource, "title">, name: string): RunSource {
  return { ...rest, title: name };
}

/** Arguments of the one-run mode. Throws on an unknown flag, a missing value or a missing --records/--out. */
export function parseCustomArgs(args: readonly string[]): CustomArgs {
  const flags = new Map<string, string>();
  for (let i = 0; i < args.length; i += 2) {
    const flag = args[i] ?? "";
    const value = args[i + 1];
    if (!CUSTOM_FLAGS.includes(flag) || value === undefined) throw new Error(`bad argument ${flag}`);
    flags.set(flag, value);
  }
  const records = flags.get("--records");
  const out = flags.get("--out");
  if (records === undefined || out === undefined) throw new Error("--records and --out are required");
  const pageBy = flags.get("--page-by");
  if (pageBy !== undefined && !/^[1-9][0-9]*$/.test(pageBy)) throw new Error("--page-by must be a positive whole number");
  const spot = flags.get("--spotlight");
  const eq = spot === undefined ? -1 : spot.indexOf("=");
  if (spot !== undefined && eq < 1) throw new Error("--spotlight must be <caseKey>=<heading>");
  const extra = flags.get("--extra");
  const source = named({
    key: flags.get("--key") ?? "custom",
    file: records.split("/").pop() ?? records,
    synthetic: false,
    ...(pageBy === undefined ? {} : { pageBy: Number(pageBy) }),
    ...(extra === undefined ? {} : { extraMethods: extra.split(",").filter((m) => m !== "") }),
    ...(spot === undefined ? {} : { spotlight: { caseKey: spot.slice(0, eq), heading: spot.slice(eq + 1) } }),
  }, flags.get("--title") ?? DEFAULT_NAME);
  return { records, out, sourceUrl: flags.get("--source-url") ?? "", source };
}

export async function buildCustom(a: CustomArgs): Promise<ReplayData> {
  return { schema: "jnj-replay/1", min_paired: MIN_PAIRED, runs: [{ ...parseRun(await Bun.file(a.records).text(), a.source), sourceUrl: a.sourceUrl }] };
}

if (import.meta.main && process.argv[2] === "--records") {
  try {
    const a = parseCustomArgs(process.argv.slice(2));
    const built = replayScript(await buildCustom(a), a.source.file);
    await Bun.write(a.out, built);
    console.log(`wrote ${a.out} (${built.length} bytes)`);
  } catch (error) {
    console.error(`${error instanceof Error ? error.message : String(error)}\n${USAGE}`);
    process.exit(2);
  }
} else if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error(`${USAGE}\nunknown arguments: ${args.join(" ")}; nothing written`);
    process.exit(2);
  }
  const built = replayScript(await buildReplay());
  if (args[0] === "--check") {
    const same = (await Bun.file(REPLAY_OUT).text().catch(() => "")) === built;
    console.log(same ? "replay data up to date" : "stale: site/replay/replay-data.js; run bun scripts/replay-data.ts");
    process.exit(same ? 0 : 1);
  }
  await Bun.write(REPLAY_OUT, built);
  console.log(`wrote site/replay/replay-data.js (${built.length} bytes)`);
}
