// Builds the replay page's data (site/replay/replay-data.js) from the repo's own record files: every case, answer,
// label and cost comes from the CSV, and the tallies and flags from src/evidence/replay.ts. Same pattern as
// scripts/uc13/little-shop.ts.
//
//   bun scripts/replay-data.ts           write the file
//   bun scripts/replay-data.ts --check   exit 1 if the committed file differs from a fresh build

import { join } from "node:path";
import { RUN_SOURCES, parseRun, type ReplayRun } from "../src/evidence/replay.ts";
import { MIN_PAIRED } from "../src/core/verdict.ts";

const ROOT = join(import.meta.dir, "..");
export const REPLAY_OUT = join(ROOT, "site", "replay", "replay-data.js");
export const REPO_URL = "https://github.com/breakoutwithai/jevnotjev";

export interface ReplayData {
  readonly schema: "jnj-replay/1";
  readonly min_paired: number;
  readonly runs: readonly (ReplayRun & { readonly sourceUrl: string })[];
}

export async function buildReplay(root = ROOT): Promise<ReplayData> {
  const runs = await Promise.all(RUN_SOURCES.map(async (s) => ({
    ...parseRun(await Bun.file(join(root, s.file)).text(), s),
    sourceUrl: `${REPO_URL}/blob/main/${s.file}`,
  })));
  return { schema: "jnj-replay/1", min_paired: MIN_PAIRED, runs };
}

const PREFIX = "window.JNJ_REPLAY = ";
const HEADER = `/*
 * GENERATED by scripts/replay-data.ts from ${RUN_SOURCES.map((s) => s.file).join(", ")}.
 * Do not edit; rerun the script. Each run's cases, answers, labels and costs as recorded, the tally after each case,
 * each method's totals, and the incomplete-evidence flags (src/evidence/replay.ts).
 */
`;

export function replayScript(d: ReplayData): string {
  return `${HEADER}${PREFIX}${JSON.stringify(d)};\n`;
}

/** Reads the data object back out of a generated data script. */
export function readReplayScript(js: string): unknown {
  const at = js.lastIndexOf(`\n${PREFIX}`) + 1;
  if (at === 0) throw new Error("no window.JNJ_REPLAY assignment");
  return JSON.parse(js.slice(at + PREFIX.length).trim().replace(/;$/, ""));
}

export const USAGE = "usage: bun scripts/replay-data.ts [--check]";

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length > 1 || (args.length === 1 && args[0] !== "--check")) {
    console.error(`${USAGE}\nunknown arguments: ${args.join(" ")}; nothing written`);
    process.exit(2);
  }
  const built = replayScript(await buildReplay());
  if (args[0] === "--check") {
    const same = (await Bun.file(REPLAY_OUT).text().catch(() => "")) === built;
    console.log(same ? "replay data up to date" : "stale: site/replay/replay-data.js; run bun scripts/replay-data.ts");
    process.exit(same ? 0 : 1);
  }
  await Bun.write(REPLAY_OUT, built);
  console.log(`wrote site/replay/replay-data.js (${built.length} bytes)`);
}
