import { createHash } from "node:crypto";

const STYLE = `:root{--bg:#e8e5df;--paper:#efe2c4;--ink:#1f0a0e;--muted:#665454;--line:rgba(31,10,14,.2);--curtain:#7b1424;--brass:#8a5f10;--sans:"Helvetica Neue",Arial,sans-serif}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:"Iowan Old Style",Georgia,serif;line-height:1.5;border-top:7px solid var(--curtain)}header{max-width:980px;margin:auto;padding:20px 24px;font-family:var(--sans)}header a{color:inherit;font-weight:700}header span{font-weight:400;color:var(--muted)}main{max-width:700px;margin:28px auto;padding:0 24px}.ticket{display:flex;justify-content:space-between;background:var(--paper);padding:22px 0 22px 30px;border:1px solid var(--brass);box-shadow:4px 5px 0 var(--line);transform:rotate(-.6deg)}.stub{border-left:2px dashed var(--brass);writing-mode:vertical-rl;padding:0 20px;font:700 11px var(--sans);letter-spacing:.18em}.eyebrow{font:700 10px var(--sans);letter-spacing:.19em;color:var(--brass);margin:0 0 12px}h1{font-size:clamp(40px,7vw,66px);line-height:1.05;margin:0}h1 em{font-weight:400}.direction{font-style:italic;color:var(--muted);font-size:20px;margin:8px 0}.intro{font-size:20px;margin:30px 0}section{background:var(--paper);border:1px solid var(--line);padding:24px;margin:20px 0}label{display:block;font:600 13px var(--sans);margin:14px 0}input{display:block;width:100%;padding:12px;margin-top:5px;border:1px solid var(--line);font:16px var(--sans)}button,.button{display:inline-block;font:600 14px var(--sans);padding:12px 16px;background:var(--curtain);border:1px solid var(--curtain);color:white;text-decoration:none;min-height:44px;cursor:pointer}button:disabled{opacity:.45;cursor:not-allowed}.note,.message{font:14px var(--sans)}.message{padding:12px;border:1px solid var(--brass)}a:focus-visible,button:focus-visible,input:focus-visible{outline:3px solid var(--brass);outline-offset:3px}`;
const STYLE_HASH = createHash("sha256").update(STYLE).digest("base64");

export function escapeHtml(value: string): string {
  return value.replace(/[&<>"']/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[char] ?? char);
}

// Layout and copy shape ported from groit apps/booth/server.js:1549-1680 at bb29d8cc.
export function renderSignInPage(next: string, message: string | null, googleConfigured: boolean, baseCsp: string): Response {
  const note = message === "signed-out" ? "You are signed out" : message === "locked" ? "Too many attempts. Try again later." : message === "google" ? "Google sign-in failed. Try again." : message === "signin" ? "Sign-in failed. Check your details and try again." : "";
  const safeNext = escapeHtml(next);
  const google = googleConfigured
    ? `<a class="button" href="/api/auth/google?next=${encodeURIComponent(next)}">Continue with Google</a>`
    : `<button type="button" disabled>Continue with Google</button><p class="note">Google sign-in is not configured.</p>`;
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sign in | Backstage Pass</title><style>${STYLE}</style></head><body><header><a href="/">Jev!Jev <span>/ The Stage</span></a></header><main><div class="ticket"><div><p class="eyebrow">ADMIT ONE / WORK IN PROGRESS</p><h1>Backstage <em>Pass</em></h1><p class="direction">A little rough. A real rehearsal.</p></div><span class="stub">BRING YOUR OWN KEYS</span></div><p class="intro">Sign in to enter Backstage.</p>${note ? `<p class="message" role="alert">${escapeHtml(note)}</p>` : ""}<section><h2>Sign in</h2>${google}<form action="/api/auth/password" method="post"><input type="hidden" name="next" value="${safeNext}"><label>Email<input type="email" name="email" autocomplete="username" required></label><label>Password<input type="password" name="password" autocomplete="current-password" required></label><button type="submit">Sign in</button></form></section></main></body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store", "x-content-type-options": "nosniff", "referrer-policy": "no-referrer", "content-security-policy": baseCsp.replace("style-src 'self'", `style-src 'self' 'sha256-${STYLE_HASH}'`) } });
}
